site_name: TextMiner-Pro Documentation
site_description: 고급 텍스트 분석을 위한 Python 패키지
site_author: asddzxqw
site_url: https://asddzxqw.github.io/textminer-pro

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference: api_reference.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

repo_name: asddzxqw/textminer-pro
repo_url: https://github.com/asddzxqw/textminer-pro
edit_uri: edit/main/docs/